/**
 * Pulls project cover photography from Pexels and writes it into `public/`.
 *
 * Run once, commit the result. The site never calls Pexels at runtime and the
 * key is never stored in the repo:
 *
 *   PEXELS_API_KEY=... node scripts/fetch-covers.mjs
 *
 * Every image is converted to greyscale on the way in. That is the decision
 * that stops six unrelated stock photos reading as six unrelated stock photos:
 * desaturated, they match the portrait and become one monochrome set. It also
 * means the WebGL plates and the DOM cards share a treatment without a shader.
 *
 * Deliberately does NOT touch `public/about/` or `public/certifications/`.
 * Those slots are records — a team photo and credential scans — and filling
 * them with stock would misrepresent things that actually happened.
 *
 * Pexels licence: free for commercial use, attribution not required. The
 * manifest is written anyway so provenance is traceable.
 */

import { execFile } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);
const PUBLIC = join(dirname(fileURLToPath(import.meta.url)), "..", "public");

const KEY = process.env.PEXELS_API_KEY;
if (!KEY) {
  console.error("Set PEXELS_API_KEY. It is not read from any file on purpose.");
  process.exit(1);
}

/**
 * Queries lean structural and architectural rather than literal. A photograph
 * of a real data centre next to a case study implies it is *that* client's
 * infrastructure, which the NDA will not allow us to imply either way.
 */
const COVERS = [
  ["agent-orchestration", "brutalist concrete architecture"],
  ["media-processing", "recording studio equipment"],
  ["document-ingestion", "library archive shelves"],
  ["ai-service-interfaces", "long exposure light trails"],
  ["carbon-credit-tokenization", "solar panels aerial view"],
  ["social-media-analytics", "abstract geometric structure"],
];

async function search(query) {
  const url = new URL("https://api.pexels.com/v1/search");
  url.searchParams.set("query", query);
  url.searchParams.set("orientation", "landscape");
  url.searchParams.set("per_page", "1");

  const response = await fetch(url, { headers: { Authorization: KEY } });
  if (!response.ok) {
    throw new Error(`Pexels ${response.status} for "${query}"`);
  }
  const { photos } = await response.json();
  if (!photos?.length) throw new Error(`No results for "${query}"`);
  return photos[0];
}

const manifest = [];

for (const [slug, query] of COVERS) {
  const photo = await search(query);
  const target = join(PUBLIC, "work", slug, "cover.jpg");

  const image = await fetch(photo.src.large2x);
  await writeFile(target, Buffer.from(await image.arrayBuffer()));

  // macOS ships this; no image dependency needed for a one-off script.
  // Quality 70 because these are greyscale and get re-encoded by next/image
  // anyway — the committed file only needs to be a good enough source.
  await run("sips", [
    // 1600 is wider than the largest slot the covers are rendered into, so
    // anything above it is bytes committed to git for nothing.
    "--resampleWidth",
    "1600",
    "-s",
    "format",
    "jpeg",
    "-s",
    "formatOptions",
    "70",
    "--matchTo",
    "/System/Library/ColorSync/Profiles/Generic Gray Profile.icc",
    target,
    "--out",
    target,
  ]);

  manifest.push({ slug, query, photographer: photo.photographer, url: photo.url });
  console.log(`${slug}  <-  ${photo.photographer}`);
}

await writeFile(
  join(PUBLIC, "work", "CREDITS.md"),
  [
    "# Cover photography",
    "",
    "Generated by `scripts/fetch-covers.mjs`. Sourced from Pexels (free for",
    "commercial use, attribution optional), converted to greyscale on download.",
    "",
    "Replace any `cover.jpg` with your own photo at the same path and it is",
    "picked up automatically — no content edit, no rerun of this script.",
    "",
    ...manifest.map((m) => `- **${m.slug}** — ${m.photographer}, ${m.url}`),
    "",
  ].join("\n"),
);

console.log(`\nWrote ${manifest.length} covers and CREDITS.md`);
